name: image-scanning
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RANCHERBOT_IMAGE_SCANNING_TOKEN }}
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: unset GOPATH
      - run: ./scripts/generate-images.sh
      - run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $(pwd)
      - run: python run.py docs/_data/cves-v2.6.csv rancher-images-sources-v2.6.txt v2.6 ${{ secrets.ISSUE_REPO }} ${{ secrets.RANCHERBOT_IMAGE_SCANNING_TOKEN }}
      - run: git config --global user.name "Image Scanning Bot"
      - run: git config --global user.email "githubaction-no-reply@rancher.com"
      - run: hasUpdate=false && if git status | grep -q "cves-v2.6.csv"; then hasUpdate=true; echo "new cves found" && git add docs/_data/cves-v2.6.csv && git commit -m "Update cves" && git push origin main; fi
